// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARXzTdVHjGLm7K2y14FMBEsFBQfPnJYAY',
    appId: '1:818193090892:web:74fa62aa92b906063227e9',
    messagingSenderId: '818193090892',
    projectId: 'studentreg-833b5',
    authDomain: 'studentreg-833b5.firebaseapp.com',
    databaseURL: 'https://studentreg-833b5-default-rtdb.firebaseio.com',
    storageBucket: 'studentreg-833b5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvHvjLD9j-XpI_pqLRHxYg42hakoo9IXQ',
    appId: '1:818193090892:android:5e3a84747b0b676a3227e9',
    messagingSenderId: '818193090892',
    projectId: 'studentreg-833b5',
    databaseURL: 'https://studentreg-833b5-default-rtdb.firebaseio.com',
    storageBucket: 'studentreg-833b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP8l_1Wt9BII8KRcx5qlI-aSOGNlkn48c',
    appId: '1:818193090892:ios:fc062ed3c29da6753227e9',
    messagingSenderId: '818193090892',
    projectId: 'studentreg-833b5',
    databaseURL: 'https://studentreg-833b5-default-rtdb.firebaseio.com',
    storageBucket: 'studentreg-833b5.appspot.com',
    iosBundleId: 'com.example.taskOneReg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP8l_1Wt9BII8KRcx5qlI-aSOGNlkn48c',
    appId: '1:818193090892:ios:ccb7cb1795ad72ed3227e9',
    messagingSenderId: '818193090892',
    projectId: 'studentreg-833b5',
    databaseURL: 'https://studentreg-833b5-default-rtdb.firebaseio.com',
    storageBucket: 'studentreg-833b5.appspot.com',
    iosBundleId: 'com.example.taskOneReg.RunnerTests',
  );
}
